# Generated by Django 4.2 on 2023-09-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_remove_result_result_isiresult_result_result"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Isiresult",
        ),
    ]
