# Generated by Django 4.2 on 2023-09-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_result_gambar"),
    ]

    operations = [
        migrations.CreateModel(
            name="recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isi", models.TextField()),
                (
                    "namaProject",
                    models.ManyToManyField(
                        related_name="recomendation", to="projects.proyek"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isi", models.TextField()),
                (
                    "namaProject",
                    models.ManyToManyField(
                        related_name="insight", to="projects.proyek"
                    ),
                ),
            ],
        ),
    ]
