# Generated by Django 4.2 on 2023-09-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_purpose_heading"),
    ]

    operations = [
        migrations.DeleteModel(
            name="purpose",
        ),
    ]
