# Generated by Django 4.2 on 2023-09-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_delete_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="purpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isi", models.TextField()),
                ("heading", models.TextField(blank=True)),
                (
                    "namaProject",
                    models.ManyToManyField(
                        related_name="purpose", to="projects.proyek"
                    ),
                ),
            ],
        ),
    ]
