# Generated by Django 4.2 on 2023-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purpose",
            name="isi",
            field=models.TextField(blank=True),
        ),
    ]
