# Generated by Django 4.2 on 2023-09-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_dataset"),
    ]

    operations = [
        migrations.CreateModel(
            name="dataPrep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("code", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                (
                    "namaProject",
                    models.ManyToManyField(
                        related_name="dataprep", to="projects.proyek"
                    ),
                ),
            ],
        ),
    ]
