# Generated by Django 4.2 on 2023-09-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_result_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataprep",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
