# Generated by Django 4.2 on 2023-09-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_alter_dataprep_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataprep",
            name="code",
            field=models.TextField(blank=True),
        ),
    ]
