# Generated by Django 4.2 on 2023-08-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("call", models.CharField(max_length=20)),
                ("locations", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=500)),
            ],
        ),
    ]
