# Generated by Django 4.2 on 2023-08-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_remove_offer_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="icon",
            field=models.CharField(default="bx bx", max_length=100),
            preserve_default=False,
        ),
    ]
