# Generated by Django 4.2 on 2023-08-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_alter_certification_certifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="year",
            field=models.CharField(max_length=25),
        ),
    ]
