# Generated by Django 4.2 on 2023-08-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_alter_school_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="projectExp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("year", models.IntegerField(max_length=15)),
                ("city", models.CharField(max_length=50)),
                ("background", models.CharField(max_length=500)),
                ("jobdesk", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="workExp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("year", models.IntegerField(max_length=15)),
                ("city", models.CharField(max_length=50)),
                ("jobdesk", models.CharField(max_length=500)),
            ],
        ),
    ]
