# Generated by Django 4.2 on 2023-08-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_projectexp_workexp"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="finish",
            field=models.DateField(default="2000-03-03"),
        ),
        migrations.AlterField(
            model_name="projectexp",
            name="year",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="workexp",
            name="year",
            field=models.CharField(max_length=15),
        ),
    ]
