# Generated by Django 4.2 on 2023-08-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0005_school_finish_alter_projectexp_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="finish",
            field=models.DateField(default="2000-03-03"),
        ),
        migrations.AddField(
            model_name="projectexp",
            name="finish",
            field=models.DateField(default="2000-03-03"),
        ),
        migrations.AddField(
            model_name="workexp",
            name="finish",
            field=models.DateField(default="2000-03-03"),
        ),
    ]
