# Generated by Django 4.2 on 2023-08-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0006_certification_finish_projectexp_finish_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectexp",
            name="jobdesk",
        ),
        migrations.RemoveField(
            model_name="workexp",
            name="jobdesk",
        ),
        migrations.AddField(
            model_name="projectexp",
            name="jobdesk1",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectexp",
            name="jobdesk2",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectexp",
            name="jobdesk3",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workexp",
            name="jobdesk1",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workexp",
            name="jobdesk2",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workexp",
            name="jobdesk3",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projectexp",
            name="finish",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="workexp",
            name="finish",
            field=models.DateField(),
        ),
    ]
