# Generated by Django 4.2 on 2023-08-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0007_remove_projectexp_jobdesk_remove_workexp_jobdesk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectexp",
            name="jobdesk4",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workexp",
            name="jobdesk4",
            field=models.TextField(blank=True),
        ),
    ]
