# Generated by Django 4.2 on 2023-08-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0008_projectexp_jobdesk4_workexp_jobdesk4"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexp",
            name="company",
            field=models.CharField(default="a", max_length=50),
            preserve_default=False,
        ),
    ]
